language: php

php:
  - '7.3'
  - '7.2'
  - '7.1'

install: composer install

script:
  - ./vendor/bin/phpunit --coverage-html coverage
  - ./vendor/bin/phpcs --standard=PSR2 --extensions=php src
  - ./vendor/bin/phpmd src text phpmd-ruleset.xml --exclude vendor --suffixes php

after_script:
  - composer export-coverage

cache:
  directories:
    - vendor

branches:
  only:
    - master
    - develop

notifications:
  email:
    on_success: never
    on_failure: change
