sudo: false
dist: trusty

cache:
  directories:
    - "$HOME/.composer/cache"
    - vendor

language: php
php:
  - '7.3'
  - '7.2'
  - '7.1'

branches:
  only:
    - master
    - develop

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - export DEV_BIN_PATH=bin
  - source $DEV_BIN_PATH/create-all-branches.sh
  - |
    # Remove Xdebug for a huge performance increase:
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - composer require --dev --no-update roots/wordpress:${WP_VERSION} wp-phpunit/wp-phpunit:${WP_VERSION}
  - composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

before_script:
  - mysql -u root -e "GRANT ALL PRIVILEGES ON $WORDPRESS_DB_NAME.* TO $WORDPRESS_DB_USER IDENTIFIED BY '$WORDPRESS_DB_PASS';"
  - mysql -u root -e "CREATE DATABASE $WORDPRESS_DB_NAME;"

script:
  - composer tests

after_script:
  - composer export-coverage

notifications:
  email:
    on_success: never
    on_failure: change
