language: php

php:
  - '7.3'
  - '7.2'
  - '7.1'

install: composer install

script:
  - composer tests

after_script:
  - composer export-coverage

cache:
  directories:
    - vendor

branches:
  only:
    - master
    - develop

notifications:
  email:
    on_success: never
    on_failure: change
